version: '3.8'
services:
    app:
        image: php:8.3-fpm
        container_name: order_api_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - order-api-network

    webserver:
        image: nginx:alpine
        container_name: order_api_webserver
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8000:80"
        networks:
            - order-api-network

networks:
    order-api-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
